# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appspesemodulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaspese',
            name='data_inserimento',
            field=models.DateTimeField(verbose_name='data added'),
        ),
    ]
