# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appspesemodulo', '0002_auto_20151231_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipipagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodopagamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=300)),
                ('dataspesa', models.DateTimeField(verbose_name=b'Data Spesa')),
                ('datainserimentospesa', models.DateTimeField(verbose_name=b'Data inserimento')),
                ('catspesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appspesemodulo.Categoriaspese')),
                ('tipopagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appspesemodulo.Tipipagamento')),
            ],
        ),
    ]
