# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appspesemodulo', '0003_tipipagamento_usertable'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='importo',
            field=models.DecimalField(decimal_places=2, default=(3.50), max_digits=9),
            preserve_default=False,
        ),
    ]
