# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appspesemodulo', '0004_usertable_importo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaspese',
            options={'ordering': ['tipologia'], 'verbose_name': 'Categoria Spesa', 'verbose_name_plural': 'Categorie di Spese'},
        ),
        migrations.AlterModelOptions(
            name='tipipagamento',
            options={'ordering': ['metodopagamento'], 'verbose_name': 'Tipo di Pagamento', 'verbose_name_plural': 'Tipi di Pagamento'},
        ),
        migrations.AlterModelOptions(
            name='usertable',
            options={'ordering': ['-dataspesa']},
        ),
        migrations.AddField(
            model_name='usertable',
            name='userLogged',
            field=models.CharField(default='Julesx', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoriaspese',
            name='data_inserimento',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'data added'),
        ),
        migrations.AlterField(
            model_name='categoriaspese',
            name='tipologia',
            field=models.CharField(max_length=200, verbose_name=b'Categoria di Spesa'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='catspesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appspesemodulo.Categoriaspese', verbose_name=b'Categoria Spesa'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='datainserimentospesa',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Data inserimento'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='tipopagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appspesemodulo.Tipipagamento', verbose_name=b'Tipo di Pagamento'),
        ),
    ]
