# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appspesemodulo', '0005_auto_20160210_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=300)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('dataspesa', models.DateTimeField(verbose_name=b'Data Spesa')),
                ('datainserimentospesa', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Data inserimento')),
                ('userLogged', models.CharField(max_length=30, verbose_name=b'Utente che ha effettuato la spesa')),
                ('catspesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appspesemodulo.Categoriaspese', verbose_name=b'Categoria Spesa')),
                ('tipopagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appspesemodulo.Tipipagamento', verbose_name=b'Tipo di Pagamento')),
            ],
            options={
                'ordering': ['-dataspesa'],
            },
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='catspesa',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='tipopagamento',
        ),
        migrations.DeleteModel(
            name='userTable',
        ),
    ]
